server:
  port: 8761


spring:
  application:
    name: zuul-eureka

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


zuul:
  prefix: /spring
  routes:
    db_service:
      path: /db-service/**
      url: http://localhost:8004
